[profile.default]
src = "src"
out = "out"
optimizer = true
libs = ["lib"]
solc_version = "0.8.24"
remappings = [
            '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
            '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
            '@chainlink/=lib/chainlink/contracts'
             ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
